---
title: "Data Manipulation"
author: "Linh Tran"
date: "9/23/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
```

## Loading data and cleaning column names

```{r loading_data}
options (tibble.print_min = 3)

litters_df = read_csv("data/FAS_litters.csv", 
                      col_types = "ccddiiii")
litters_df = clean_names(litters_df)

pups_df = read_csv("data/FAS_pups.csv",
                   col_types = "ciiiii")
pups_df = clean_names(pups_df)
```

## `select` 

Choose some columns and not others.

```{r}
select(litters_df, group, gd0_weight)
```

Select from gd0_weight to gd_of_birth
```{r}
select(litters_df, group, gd0_weight: gd_of_birth)
```

Specify what we want to lose (litter number)
```{r}
select(litters_df, -litter_number)
```

Renaming columns
```{r}
select(litters_df, gd_weight_0 = gd0_weight, gd_weight_18 = gd18_weight)
```

Can also use rename()
```{r}
rename(litters_df, gd_weight_0 = gd0_weight, gd_weight_18 = gd18_weight)
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

Relocate litter number columne to the beginning
```{r}
relocate(litters_df, litter_number)
```

