---
title: "data_import"
author: "Linh Tran"
date: "9/23/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

Read in the litters dataset. 

```{r litters_dataset}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
names(litters_df)
```

Read in the pups dataset.

```{r pups_dataset}
pups_df = read_csv("data/FAS_pups.csv")
janitor::clean_names(pups_df)
pups_data = read_csv("./data/FAS_pups.csv", 
                     col_types = cols(Sex = col_character())
                     )
pups_data
pups_data = read_csv("data/FAS_pups.csv", 
                     col_types = "cciiii")
pups_data
```

## Take a look at the data

Printing in the console.

```{r}
litters_df
```

```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```


## Options to read_csv

check out `?read_csv()` for more information. 

## Other file formats

Read in an excel file. 

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
```

Read in a SAS file.

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

## Comparison with Base R

what about `read.csv` ...?

```{r}
litters_base = read.csv("data/FAS_litters.csv")
litters_readr = read_csv("data/FAS_litters.csv")
litters_base
litters_readr
```

## Exporting data

Export the mlb sub-table.

```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv")
```
